#!/bin/bash
module load vcfanno
module load parallel

DEFNJOBS=6
NJOBS=${NJOBS:-${DEFNJOBS}}

readonly IN_DIR=./merged
readonly OUT_DIR=./annotated

function infile_outfile_from_infile {
    while read infile
    do
        local base=$( basename $infile )
        local pcawg1id=$( echo $base | cut -f 1 -d . )
        local pancanid=$( ../scripts/pcawg1id_to_pancanid.sh ${pcawg1id} )

        local outfile=${OUT_DIR}/${pcawg1id}.${variant}.master.vcf 
        echo ${infile} ${outfile}
    done 
}

for variant in "snv_mnv" "indel"
do
    ls ${IN_DIR}/*.${variant}.master.vcf | infile_outfile_from_infile | parallel -j ${NJOBS} --colsep " " ./annotate_one_file {1} {2} ${variant}
done
