#!/bin/bash
module load vcfanno

readonly IN_DIR=./merged
readonly OUT_DIR=./annotated

function renamefields {
    local filename=$1
    sed -i -e 's/3pContext/wgs_3pContext/g' \
           -e 's/5pContext/wgs_5pContext/g' \
           -e 's/GermIndelDist/wgs_GermIndelDist/g' \
           -e 's/NormalEvidenceReads/wgs_NormalEvidenceReads/g' \
           -e 's/NormalReads/wgs_NormalReads/g'  \
           -e 's/NormalTotalDepth/wgs_NormalTotalDepth/g' \
           -e 's/NormalVAF/wgs_NormalVAF/g' \
           -e 's/NormalVarDepth/wgs_NormalVarDepth/g' \
           -e 's/RepeatRefCount/wgs_RepeatRefCount/g'  \
           -e 's/RepeatUnit/wgs_RepeatUnit/g'  \
           -e 's/TumorVAF/wgs_TumorVAF/g' \
           -e 's/TumourReads/wgs_TumorReads/g'  \
           -e 's/TumorVarDepth/wgs_TumorVarDepth/g' \
           -e 's/TumourAvgVarBaseQ/wgs_TumorAvgVarBaseQ/g'  \
           -e 's/TumourAvgVarMapQ/wgs_TumorAvgVarMapQ/g' \
           -e 's/TumourAvgVarPosn/wgs_TumorAvgVarPosn/g' \
           -e 's/TumourEvidenceReads/wgs_TumorEvidenceReads/g'  \
           -e 's/TumorTotalDepth/wgs_TumorReads/g' \
           -e 's/TumorTotalDepth/wgs_TumorTotalDepth/g'  \
           -e 's/SOMATIC/muse_feature/g'  \
           ${filename}
}

for variant in "snv_mnv" "indel"
do
    for file in ${IN_DIR}/*.${variant}.master.vcf
    do
        base=$( basename $file )
        pcawg1id=$( echo $base | cut -f 1 -d . )
        pancanid=$( ../scripts/pcawg1id_to_pancanid.sh ${pcawg1id} )

        TMPFILE1=${OUT_DIR}/${pcawg1id}.${variant}.tmp1.vcf 
        TMPFILE2=${OUT_DIR}/${pcawg1id}.${variant}.tmp2.vcf 

        echo -n "${variant}: ${pcawg1id} "
        # generate by-file annotation configuration file
        sed -e "s/@@SAMPLE@@/${pancanid}/" annotation/${variant}_annotations.conf.template > ${OUT_DIR}/${pcawg1id}.${variant}_annotations.conf

        # step 1: add dbsnp, cosmic, gencode
        echo -n " dbsnp/cosmic/gencode "
        vcfanno -p 4 -lua annotation/custom.lua annotation/dbsnp+cosmic+gencode.conf ${file} 2>> logs/annotate_errs.log \
            | sed -e 's/gencode=[A-Za-z,]*;//' \
            > ${TMPFILE1}

        # step 2: add uniform snv annotations, muse-as-feature
        echo -n " uniform annotations "
        vcfanno -p 4 ${OUT_DIR}/${pcawg1id}.${variant}_annotations.conf ${TMPFILE1} \
            > ${TMPFILE2} 2>> logs/annotate_errs.log

        # step 3: calculate VAFs from uniform snv annotations
        if [ "$variant" == "snv_mnv" ] 
        then
            echo -n " vafs "
            vcfanno -p 4 -lua annotation/custom.lua annotation/vaf.conf ${TMPFILE2} \
                > ${OUT_DIR}/${pcawg1id}.${variant}.master.vcf 2>> logs/annotate_errs.log
        else
            cp ${TMPFILE2} ${OUT_DIR}/${pcawg1id}.${variant}.master.vcf 
        fi
        echo ""

        rm ${TMPFILE1} ${TMPFILE2}
        rm ${OUT_DIR}/${pcawg1id}.${variant}_annotations.conf
        renamefields ${OUT_DIR}/${pcawg1id}.${variant}.master.vcf 
    done
done
