#!/bin/bash

module load gcc/4.8.1 python/2.7.2 openblas python-packages/2

readonly PROCESSED=/.mounts/labs/simpsonlab/users/jdursi/pcawg-validation-63/processed/
readonly NEWDATA=./processed
readonly OUTPUT=./merged

function rename {
    sed -e "s/${sample}//g" -e "s/${pcawg1id}//g" \
        -e 's/\.[0-9]*\.somatic\.snv_mnv\.vcf//g' -e 's/_SNV.vcf//g' \
        -e 's/_annotated_//g' \
        -e 's/_indel\.vcf//g' -e 's/\.[0-9]*\.somatic\.indel\.vcf//g' \
        -e 's/dkfz_embl/dkfz/g' \
        -e 's/\.mda_hgsc_gatk_muse/mda_hgsc_gatk_muse/g' \
        -e 's/\.adiscan/adiscan/g' \
        -e 's/\.lohcomplete/lohcomplete/g' \
        -e 's/\.oicr_sga/oicr_sga/g' \
        -e 's/\.broad_mutect/broad_mutect/g' \
        -e 's/broad\([^_]\)/broad_snowman\1/g' \
        -e 's/broad$/broad_snowman/g' \
        -e 's/tmp\.oicr_bl/oicr_bl/g' \
        -e 's/\.smufin/smufin/g' \
        -e 's/\.novobreak/novobreak/g' \
        -e 's/\.crg_clindel/crg_clindel/g' \
        -e 's/\.genomon_itdetector/genomon/g' \
        -e 's/\.wustl/wustl/g'
}

samples=$( ls "${NEWDATA}"/*vcf.gz | xargs -n 1 basename | cut -f 1 -d _ | sort | uniq )
for variant_type in "snv_mnv" "indel"
do
    newfile_type=$variant_type
    if [ "$variant_type" == "snv_mnv" ]
    then 
        newfile_type="SNV"
    fi
    for sample in $samples
    do
        pcawg1id=$( ../scripts/pancanid_to_pcawg1id.sh $sample )
        echo "$variant_type $pcawg1id"
        otherfiles=$( ls ${PROCESSED}/*/${pcawg1id}*.somatic.${variant_type}.vcf.gz | grep -v sanger | grep -v dkfz | grep -v oicr_bl )

        oicr_bl=$( ls ${PROCESSED}/oicr_bl/${pcawg1id}*.somatic.${variant_type}.vcf.gz 2> /dev/null )
        if [ ! -z "$oicr_bl" ] && [ -f "$oicr_bl" ]
        then
            zcat $oicr_bl | sed -e '/^##MuTect/d' -e '/=$/d' > merged/tmp.oicr_bl.vcf
            oicr_bl=merged/tmp.oicr_bl.vcf
        fi

        otherfiles="${otherfiles} ${oicr_bl}"

        mergevcf ${NEWDATA}/${sample}*{broad,sanger,dkfz}*${newfile_type}*vcf.gz $otherfiles \
                 | rename \
                 > merged/${pcawg1id}.${variant_type}.master.tmp

        grep "^#" merged/${pcawg1id}.${variant_type}.master.tmp  \
            > merged/${pcawg1id}.${variant_type}.master.vcf

        grep -v "^#" merged/${pcawg1id}.${variant_type}.master.tmp \
            | sort -k1,1d -k2,2n \
            >> merged/${pcawg1id}.${variant_type}.master.vcf

        rm merged/${pcawg1id}.${variant_type}.master.tmp
        rm -f merged/tmp.oicr_bl.vcf
    done
done
