#!/bin/bash
#
# Merges the calls from the validation data with the original 
# WGS master VCFS, to produce a result that has both the validation
# result and the annotations for the WGS data
#
# The bad news is that it has the Callers= info field in twice,
# but parsers seem to be able to handle this

# input VCF DIR
# can be overridden at commandline, eg VCFDIR=vcfs ./run-call.sh
DEFVCFDIR=vcfs/germline-realigned
# output dir
DEFCOMBINEDIR=combined/newmasters
# directory for original master vcfs
#DEFWGSDIR=../validation_63_sftp_mirror/masked_repeats/somatic/
DEFWGSDIR=./newmasters/annotated

readonly VCFDIR=${VCFDIR-${DEFVCFDIR}}
readonly COMBINEDIR=${COMBINEDIR-${DEFCOMBINEDIR}}
readonly WGSDIR=${WGSDIR-${DEFWGSDIR}}

echo "input directory:  ${VCFDIR}"
echo "output directory: ${COMBINEDIR}"
echo "wgs directory:    ${WGSDIR}"

for file in ${VCFDIR}/*.vcf
do
    base=$( basename $file .vcf )
    masterfile=${WGSDIR}/${base}.master.vcf
    if [ -f $masterfile ] && [ ! -f ${COMBINEDIR}/${base}.vcf ]
    then
        qsub -cwd -e logs -o logs -N merge_${base} ./scripts/one-merge-vcf.sh \
            ${file} ${WGSDIR} ${COMBINEDIR}
    fi
done 
