#!/bin/bash
while read -r line || [[ -n "$line" ]]; do
    items=(${line//	/ })

    normal=${items[1]}
    tumour=${items[2]}
    donor=${items[0]}

    for vartype in snv_mnv indel
    do
        mpileupfile=mpileups/${donor}.${vartype}.mpileup
        if [ -f $mpileupfile ]
        then
            qsub -cwd -e logs -o logs -l h_vmem=4g ./scripts/one-call.sh \
                ${mpileupfile} beds/bysample/${donor}.${vartype}_targets.gz \
                vcfs/${donor}.${vartype}.vcf
        fi
    done
done < metadata/sample-directory.txt
