#!/bin/bash

mkdir -p selected-variants/annotated/

while read -r line || [[ -n "$line" ]]; do
    items=(${line//	/ })

    normal=${items[1]}
    tumour=${items[2]}
    donor=${items[0]}

    if [ -f remappedbams/${normal} ] && [ -f remappedbams/${tumour} ] 
    then
        for vartype in snv_mnv indel
        do
            if [ -f selected-variants/somatic/${donor}.${vartype}.selected.vcf ]
            then
                qsub -cwd -e logs -o logs -l h_vmem=4g -pe smp 5 \
                    ./scripts/one-sga-annotate.sh \
                    vcfs/${donor}.${vartype}.vcf remappedbams/${normal} remappedbams/${tumour} \
                    selected-variants/annotated/${donor}.${vartype}.selected.annotated.vcf
            fi
        done
    fi
done < metadata/sample-directory.txt
