#!/bin/bash
while read -r line || [[ -n "$line" ]]; do
    items=(${line//	/ })

    normal=${items[1]}
    tumour=${items[2]}
    donor=${items[0]}

    if [ -f remappedbams/${normal} ] && [ -f remappedbams/${tumour} ]
    then
        for vartype in snv_mnv indel
        do
            qsub -cwd -e logs -o logs -l h_vmem=8g ./scripts/one-mpileup.sh \
                remappedbams/${normal} remappedbams/${tumour} \
                beds/Array_2_${vartype}_inflated.bed.gz beds/bysample/${donor}.${vartype}_targets.gz 
        done
    fi
done < metadata/sample-directory.txt
