#!/bin/bash

mkdir -p vcfs/annotated

while read -r line || [[ -n "$line" ]]; do
    items=(${line//	/ })

    normal=${items[1]}
    tumour=${items[2]}
    donor=${items[0]}

    if [ -f remappedbams/${normal} ] && [ -f remappedbams/${tumour} ] 
    then
        for vartype in snv_mnv indel
        do
            if [ -f vcfs/${donor}.${vartype}.vcf ]
            then
                qsub -cwd -e logs -o logs -l h_vmem=4g -pe smp 4 \
                    ./scripts/one-sga-annotate.sh \
                    vcfs/${donor}.${vartype}.vcf remappedbams/${normal} remappedbams/${tumour} \
                    vcfs/annotated/${donor}.${vartype}.${annotated}.vcf
            fi
        done
    fi
done < metadata/sample-directory.txt
