#!/bin/bash

#READCOUNTDIR=readcounts/germline-realigned
READCOUNTDIR=readcounts
BAMDIR=remappedbams
#BAMDIR=germ-indel-realigned

while read -r line || [[ -n "$line" ]]; do
    items=(${line//	/ })

    normal=${items[1]}
    tumour=${items[2]}
    donor=${items[0]}

    if [ -f ${BAMDIR}/${normal} ] && [ -f ${BAMDIR}/${tumour} ] 
    then
        for vartype in indel
        do
            if [ -f selected-variants/somatic/${donor}.${vartype}.selected.vcf ]
            then
                qsub -cwd -e logs -o logs -l h_vmem=4g -pe smp 5 \
                    ./scripts/one-sga-annotate.sh \
                    selected-variants/somatic/${donor}.${vartype}.selected.vcf \
                    ${BAMDIR}/${normal} ${BAMDIR}/${tumour} \
                    ${READCOUNTDIR}/${donor}.${vartype}.vcf
            fi
        done
    fi
done < metadata/sample-directory.txt
