#!/bin/bash

readonly input_bams=$( find ingest-bams -name "*.bam" )

readonly FASTQDIR=fastqs
readonly REMAPPEDDIR=remappedbams
readonly INDELREALIGNEDDIR=germ-indel-realigned

for input_bam in ${input_bams}
do
    bamname=$( basename $input_bam )
    base=${bamname//.bam/}

    if [ ! -d ${FASTQDIR}/${base} ]
    then
        qsub -cwd -e logs -o logs -l h_vmem=8g -N fastqs${base} \
            ./scripts/one_bam_to_fastq.sh ${input_bam} ${FASTQDIR}
    fi

    if [ ! -f ${REMAPPEDDIR}/${bamname} ]
    then
        qsub -cwd -e logs -o logs -N bwamem${base} \
            -hold_jid fastqs${base} \
            -pe smp 2 -l h_vmem=8g \
            ./scripts/one_realign_fastqs.sh \
                ${FASTQDIR}/${base} \
                ${REMAPPEDDIR}/${bamname} 2
    fi
done
