#!/bin/bash
READCOUNTSDIR=readcounts/germline-realigned
VCFDIR=vcfs/germline-realigned

mkdir -p ${VCFDIR}

while read -r line || [[ -n "$line" ]]; do
    items=(${line//	/ })

    normal=$( basename ${items[1]} .bam )
    tumour=$( basename ${items[2]} .bam )
    donor=${items[0]}

    for vartype in snv_mnv indel
    do
        qsub -cwd -e logs -o logs -l h_vmem=4g ./scripts/one-call.sh \
            selected-variants/somatic/${donor}.${vartype}.selected.vcf \
            ${READCOUNTSDIR}/${normal}.${vartype}.rc ${READCOUNTSDIR}/${tumour}.${vartype}.rc \
            ${VCFDIR}/${donor}.${vartype}.vcf
    done
done < metadata/sample-directory.txt
