#!/bin/bash

BAMDIR=germ-indel-realigned
READCOUNTDIR=readcounts/germline-realigned/gatk

while read -r line || [[ -n "$line" ]]; do
    items=(${line//	/ })

    normal=${items[1]}
    tumour=${items[2]}
    donor=${items[0]}
    target=${BAMDIR}/${donor}.intervals 

    if [ -f ${BAMDIR}/${normal} ] && [ -f ${BAMDIR}/${tumour} ] 
    then
        for vartype in indel
        do
            if [ -f selected-variants/somatic/${donor}.${vartype}.selected.vcf ] && [ ! -f ${READCOUNTDIR}/${donor}.${vartype}.vcf ]
            then
                if [ ! -f selected-variants/somatic/gatk-format/${donor}.${vartype}.selected.vcf ]
                then
                    ./scripts/vcf-to-gatk-vcf.sh selected-variants/somatic/${donor}.${vartype}.selected.vcf selected-variants/somatic/gatk-format/${donor}.${vartype}.selected.vcf 
                fi
                qsub -cwd -e logs -o logs -l h_vmem=4g -pe smp 4 \
                    ./scripts/one-haplotypecaller-annotate.sh \
                    selected-variants/somatic/gatk-format/${donor}.${vartype}.selected.vcf \
                    ${BAMDIR}/${normal} ${BAMDIR}/${tumour} ${target} \
                    ${READCOUNTDIR}/${donor}.${vartype}.vcf
            fi
        done
    fi
done < metadata/sample-directory.txt
