#!/bin/bash

OUTDIR=germ-indel-realigned
mkdir -p ${OUTDIR}
while read -r line || [[ -n "$line" ]]; do
    items=(${line//	/ })

    normal=${items[1]}
    tumour=${items[2]}
    donor=${items[0]}

    vcf=germline-calls/union/${donor}.vcf
    if [ -f ${vcf} ]
    then
        target=${OUTDIR}/${donor}.intervals 
        if [ ! -f ${target} ]
        then
            qsub -cwd -e logs -o logs -l h_vmem=8g -N targets-${donor} \
                ./scripts/gen-targets.sh ${vcf} ${target}
        fi
        for bam in ${normal} ${tumour} 
        do
            if [ -f remappedbams/${bam} ] 
            then
                qsub -cwd -e logs -o logs -l h_vmem=8g \
                    -hold_jid targets-${donor} \
                    ./scripts/one-indelrealign.sh \
                    remappedbams/${bam} ${vcf} \
                    ${target} germ-indel-realigned/${bam}
            fi
        done
    fi
done < metadata/sample-directory.txt
