#!/bin/bash
while read -r line || [[ -n "$line" ]]; do
    items=(${line//	/ })

    normal=$( basename ${items[1]} .bam )
    tumour=$( basename ${items[2]} .bam )
    donor=${items[0]}

    for vartype in snv_mnv indel
    do
        qsub -cwd -e logs -o logs -l h_vmem=4g ./scripts/one-call.sh \
            selected-variants/somatic/${donor}.${vartype}.selected.vcf \
            readcounts/${normal}.${vartype}.rc readcounts/${tumour}.${vartype}.rc \
            vcfs/${donor}.${vartype}.vcf
    done
done < metadata/sample-directory.txt
