#!/bin/bash

sample=""
while read line
do
    if [ ${line:0:1} != "#" ]
    then
        IFS=' ' read -a cols <<< $line
        cursample=${cols[1]}
        IFS='_' read -a coords1 <<< ${cols[2]}
        IFS='_' read -a coords2 <<< ${cols[3]}
        if [ "${cursample}" != "${sample}" ]
        then
            sample=$cursample
            pairlabel=$( grep $cursample ../metadata/sample_metadata.csv | cut -f 16 -d "," )
            infile=../master_nohally/${pairlabel}.snv_mnv.master.vcf
            outfile=${pairlabel}.snv_mnv.evolution.vcf
            head -n 1 $infile > $outfile
        fi
        grep "^${coords1[0]}	${coords1[1]}	" $infile | head -1 >> $outfile
        grep "^${coords2[0]}	${coords2[1]}	" $infile | head -1 >> $outfile
    fi
done < morris-pairs.txt
